/**
 * Workflow protocol content, fetched on demand via knit_get_workflow.
 *
 * The thin CLAUDE.md generated by claude-md.ts intentionally does NOT
 * include this content — it would tax every session with ~10KB of always-
 * resident protocol text. Instead, CLAUDE.md tells the agent "call
 * knit_get_workflow(phase) for protocol depth", and the agent pulls
 * only the section it actually needs for the current phase.
 *
 * Each phase string returns a self-contained block. They're decision aids,
 * not commandments — the v2 protocol assumes Claude has judgment.
 */

export const WORKFLOW_SECTIONS = [
  'overview',
  'tier',
  'phases',
  'research',
  'ideate',
  'plan',
  'execute',
  'optimize',
  'review',
  'tdd',
  'learn',
  'handoff',
  'ship',
  'tools',
] as const;

export type WorkflowSection = typeof WORKFLOW_SECTIONS[number];

export interface WorkflowContext {
  /** Project's typecheck/lint/test/build commands, if known. */
  buildCommands?: {
    typecheck?: string;
    lint?: string;
    test?: string;
    build?: string;
  };
}

/** Return the content for a workflow section, or null if not recognized. */
export function getWorkflowSection(phase: string, ctx: WorkflowContext = {}): string | null {
  const normalized = phase.toLowerCase().trim();
  const fn = SECTIONS[normalized as WorkflowSection];
  return fn ? fn(ctx) : null;
}

/** List all section names + one-line descriptions. */
export function listWorkflowSections(): { name: string; description: string }[] {
  return [
    { name: 'overview', description: 'What the protocol is and how to navigate it.' },
    { name: 'tier', description: 'The four tiers (Inquiry / Trivial / Standard / Complex) as a decision aid.' },
    { name: 'phases', description: 'The 6-phase protocol overview + routing per tier.' },
    { name: 'research', description: 'Phase 1 — gather context, name affected files + domains.' },
    { name: 'ideate', description: 'Phase 2 (Complex only) — propose ≥2 approaches with trade-offs.' },
    { name: 'plan', description: 'Phase 3 (Complex only) — file-level plan + plan mode rules.' },
    { name: 'execute', description: 'Phase 4 — write the code. TDD for features, repro-first for bugs.' },
    { name: 'optimize', description: 'Phase 5 — parallel review agents with role briefings.' },
    { name: 'review', description: 'Phase 6 — gates pass before commit.' },
    { name: 'tdd', description: 'RED → GREEN → REFACTOR cycle in detail.' },
    { name: 'learn', description: 'Quality-gated LEARN — when to record, when to skip.' },
    { name: 'handoff', description: 'Session handoff when context degrades.' },
    { name: 'ship', description: 'Commit format + PR flow + production checklist.' },
    { name: 'tools', description: 'Knit MCP tools reference — what each is for.' },
  ];
}

// ── Section content ──────────────────────────────────────────────

const SECTIONS: Record<WorkflowSection, (ctx: WorkflowContext) => string> = {
  overview,
  tier,
  phases,
  research,
  ideate,
  plan,
  execute,
  optimize,
  review,
  tdd,
  learn,
  handoff,
  ship,
  tools,
};

function overview(_: WorkflowContext): string {
  return `# Engram workflow — overview

This protocol is a decision aid. Read once, follow loosely, escalate when something doesn't fit. The principle: engram gives you data; you make the calls.

**Navigation:** call \`knit_get_workflow({phase})\` with any of:
- \`overview\` (this) · \`tier\` · \`phases\`
- \`research\` · \`ideate\` · \`plan\` · \`execute\` · \`optimize\` · \`review\`
- \`tdd\` · \`learn\` · \`handoff\` · \`ship\` · \`tools\`

Start of every session: call \`knit_load_session\` first. It returns prior sessions, learnings, false positives, project knowledge in one round trip.

When in doubt: under-classify. Easier to escalate mid-task than to downgrade.`;
}

function tier(_: WorkflowContext): string {
  return `# Tier classification — you decide, engram informs

Four tiers. You read the user's message and decide. No regex, no auto-rules.

| Tier | Smell | What you do |
|------|-------|-------------|
| **Inquiry** | Read-only. "What", "where", "audit", "explain", "status". | Just answer. No phases, no LEARN unless something durable surfaced. |
| **Trivial** | Single obvious change (typo, version bump, one-line fix). | EXECUTE → verify → done. |
| **Standard** | Bug fix, single-file feature, single domain. | RESEARCH → EXECUTE → OPTIMIZE → REVIEW. |
| **Complex** | Cross-domain, touches types/auth/money, high-fanout file, new feature with unclear shape, **or a single user request that will span more than one commit / PR**. | Full 6 phases. Auto-enter plan mode on RESEARCH. |

Signals to consult before classifying (call any of these):
- \`knit_find_fanout\` — is the file central?
- \`knit_search_learnings\` — have we done this before?
- \`knit_query_dependents\` — what depends on what I'd touch?
- \`knit_search_sessions\` — did a past session tackle something similar?

**Multi-commit arcs.** If a single user request will span more than one commit or PR, the *arc* is Complex even if individual commits inside it are Standard or Trivial. Enter plan mode at the start of the arc.`;
}

function phases(_: WorkflowContext): string {
  return `# The 6-phase protocol

\`\`\`
RESEARCH → IDEATE → PLAN → EXECUTE → OPTIMIZE → REVIEW
    ↑                                              |
    └──────────────── LEARN ←──────────────────────┘
\`\`\`

Routing by tier:

| Tier | Phases |
|------|--------|
| Inquiry | (none — just answer) |
| Trivial | EXECUTE → verify |
| Standard | RESEARCH → EXECUTE → OPTIMIZE → REVIEW |
| Complex | RESEARCH → IDEATE → PLAN → EXECUTE → OPTIMIZE → REVIEW |

Each phase has one quality gate. Don't move on until it passes. Call \`knit_get_workflow({phase})\` for the depth on any phase.`;
}

function research(_: WorkflowContext): string {
  return `# RESEARCH (Standard + Complex)

Goal: understand what you're touching before you touch it.

**Standard tasks:** read the affected files directly. Check cross-domain ripple via \`knit_query_dependents\`. Pull relevant past sessions via \`knit_search_sessions\` if the area has history.

**Complex tasks:** spawn \`code-explorer\` agents per affected domain in parallel. Each scout reports complexity + risks. Use \`knit_find_fanout\` to spot universal-contract files.

**Gate:** can you name every file and domain that will be touched? If no, read more. If yes, proceed.

**Avoid:** speculative file reads. Avoid reading every file in the import graph "just in case." Read what the change demands, then stop.`;
}

function ideate(_: WorkflowContext): string {
  return `# IDEATE (Complex only)

Goal: surface at least 2 approaches with trade-offs before committing to one.

1. Launch domain heads in parallel. Each head proposes an approach for its domain + risks.
2. Synthesize into 2+ distinct options. Make them genuinely different — same approach with two coats of paint isn't IDEATE.
3. Present options with trade-offs (complexity / risk / reversibility / scope).

**Gate:** user picks an approach.

For Standard, skip IDEATE — pick the obvious approach and state it out loud. User can override.`;
}

function plan(_: WorkflowContext): string {
  return `# PLAN (Complex only — auto plan mode)

**Plan mode auto-fires by phase, not by user keyword.** You enter plan mode when you decide to enter RESEARCH or PLAN. The user doesn't need to say "plan."

- **Inquiry / Trivial** → never plan mode.
- **Standard** → rarely; only if RESEARCH reveals unexpected complexity.
- **Complex** → plan mode opens at the start of RESEARCH. Stay in plan mode through IDEATE and PLAN. User's approval is required to **exit** plan mode (before EXECUTE).

What to produce in PLAN:
1. File-level: exact files to create / modify / delete.
2. Ordering: which domain goes first, what's sequential vs parallel.
3. Test plan: how to verify the work end-to-end.
4. Risk note: what could break + rollback path.

**Gate:** user says "go" / "approved" / "do it." After approval, exit plan mode and execute.`;
}

function execute(ctx: WorkflowContext): string {
  const buildHint = ctx.buildCommands?.typecheck
    ? `\n\nMilestone check (every ~5 edits): run \`${ctx.buildCommands.typecheck}\` — still green?`
    : '';
  return `# EXECUTE

Follow the approved plan strictly. No scope creep — surprises go into LEARN, not into the diff.

**New features:** TDD when applicable (see \`knit_get_workflow({phase: "tdd"})\`). Failing test → minimum impl → refactor.

**Bug fixes:** reproduce first. Write the failing test that captures the bug. Fix. Run full suite. No regressions.

**Cross-domain changes:** follow the cross-domain ripple rules from RESEARCH. If a type contract changes, all downstream domains get notified.${buildHint}

**Avoid:**
- Adding error handling for cases that can't happen.
- Adding comments that explain WHAT (well-named code already does that).
- Backwards-compat shims when the code can just change.
- Half-finished implementations. Either it works end-to-end or it doesn't ship.`;
}

function optimize(_: WorkflowContext): string {
  return `# OPTIMIZE (Standard + Complex)

Spawn review agents in parallel. Standard: 1–2 agents. Complex: as many as affected domains.

**Role briefing replaces frozen Domain Context Objects.** Each spawned agent gets a short briefing, not a 3K-token DCO. The agent has MCP access and pulls depth on demand.

Briefing template:
> You are a {role} for files X, Y, Z. Task: {one sentence}.
> Project brain available: \`knit_query_dependents\`, \`knit_get_false_positives\`, \`knit_search_learnings\`, \`knit_search_sessions\`. Call them if you need depth.
> Report findings as: severity / file / line / issue / suggestion.

Before passing false positives — filter to those whose file paths overlap the agent's task. Don't dump all entries; pass the 3 that apply.

Findings sorted CRITICAL / HIGH / MEDIUM / LOW.

**Gate:** zero CRITICAL findings. All HIGH addressed (fixed or explicitly deferred with reason).`;
}

function review(ctx: WorkflowContext): string {
  const gates: string[] = [];
  if (ctx.buildCommands?.typecheck) gates.push(`- \`${ctx.buildCommands.typecheck}\``);
  if (ctx.buildCommands?.lint) gates.push(`- \`${ctx.buildCommands.lint}\``);
  if (ctx.buildCommands?.test) gates.push(`- \`${ctx.buildCommands.test}\``);
  if (ctx.buildCommands?.build) gates.push(`- \`${ctx.buildCommands.build}\``);
  const gatesBlock = gates.length > 0
    ? `\n\nGates for this project:\n${gates.join('\n')}`
    : '';

  return `# REVIEW (Standard + Complex)

**Layer 1 — automated gates.** typecheck + lint + test + build all green. If anything fails: fix, re-run.${gatesBlock}

**Layer 2 — functional verification.** If browser QA tools are available and the task touches UI or API, navigate the change end-to-end. Take screenshots as proof. If unavailable, note "browser verification skipped" and continue.

**Layer 3 — ship readiness (Complex + PR only):**
- Plan-vs-done diff: anything missed?
- Regression check: did existing functionality break?
- Confidence signal: "ready to ship" only when ALL layers pass.`;
}

function tdd(_: WorkflowContext): string {
  return `# TDD workflow

**New feature:**
1. RED — write a test that describes the expected behavior. Run tests. New test MUST fail. If it passes, it isn't testing anything new.
2. GREEN — write the simplest code that makes the test pass. No extras, no optimization, no cleanup.
3. REFACTOR — clean up. Extract helpers, improve naming, kill duplication. Run tests after EVERY change.
4. VERIFY COVERAGE — does the new code have tests? Are edge cases covered?

**Bug fix:**
1. REPRODUCE — find the exact input that triggers the bug.
2. WRITE FAILING TEST — captures the bug.
3. FIX — minimum change to make the test pass.
4. VERIFY — full test suite, no regressions.

**When NOT to TDD:**
- Trivial-tier work (typo, config, version bump).
- Doc updates.
- Behavior-preserving refactors (run existing tests).`;
}

function learn(_: WorkflowContext): string {
  return `# LEARN — opportunistic, not mandatory

**Default: don't record a learning.** Most tasks produce no durable insight.

Record one only when **all** are true:
- A non-obvious fact emerged (the kind future-you would forget by next month).
- The lesson generalizes to a hypothetical future task.
- You can name a specific tag where someone would search for it.

Quality check before \`knit_record_learning\`:
> If session N+1 searched for this tag, would this entry save them time?

If no — don't write. Manufactured learnings hurt the hit rate by burying real ones.

If a task finishes with no learning recorded — that's correct, not a failure.

**Sessions vs learnings.** Two different tools:
- \`knit_record_learning\` — durable, reusable insight (Stripe webhook signature rules).
- \`knit_save_session_summary\` — what this session accomplished (refactored auth middleware). Opt-in, narrative.

Use both. They serve different searches.`;
}

function handoff(_: WorkflowContext): string {
  return `# Session handoff

When context degrades — circular debugging, repeated failures, post-compaction confusion — call \`knit_save_handoff\` with:

- **goal** — what we're trying to accomplish
- **current_state** — where we are right now
- **files_in_flight** — what's been modified
- **what_changed** — commits and edits since session start
- **failed_attempts** *(mandatory)* — what was tried and why it failed. This is the load-bearing field that prevents the next session from repeating mistakes.
- **decisions_made** — choices and their reasoning
- **next_step** — the ONE most important thing to do next

Then tell the user to start a fresh session. The next session's \`knit_load_session\` will surface the handoff first.

**Never auto-handoff.** Try compacting context first. Handoff is for genuinely stuck.`;
}

function ship(ctx: WorkflowContext): string {
  const gates = [];
  if (ctx.buildCommands?.typecheck) gates.push(ctx.buildCommands.typecheck);
  if (ctx.buildCommands?.lint) gates.push(ctx.buildCommands.lint);
  if (ctx.buildCommands?.test) gates.push(ctx.buildCommands.test);
  if (ctx.buildCommands?.build) gates.push(ctx.buildCommands.build);
  const gatesLine = gates.length > 0
    ? `\n\nPre-commit (all must pass): \`${gates.join(' && ')}\``
    : '';

  return `# Commit & ship${gatesLine}

**Commit format:**
\`\`\`
<type>: <description>

<optional body — what and why, not how>
\`\`\`
Types: \`feat\`, \`fix\`, \`refactor\`, \`docs\`, \`test\`, \`chore\`, \`perf\`.

**PR flow:**
1. Atomic commits — one concern per commit.
2. Push to feature branch.
3. PR with 1–3 bullet summary + test plan.
4. Squash merge to main, delete branch.

**Production checklist** (only when shipping to prod, not every PR):
- No secrets in code or git history (\`git log -p --all -S "sk-"\`).
- \`.env\` in \`.gitignore\`; \`.env.example\` exists with placeholders.
- All user input validated at system boundaries.
- Build succeeds clean: \`rm -rf node_modules && npm ci && npm run build\`.
- Auth on protected routes; rate limiting on auth/submission endpoints.
- Verify production loads post-deploy. Check error monitoring.`;
}

function tools(_: WorkflowContext): string {
  return `# Knit MCP tools — reference

**Read the brain** (cheap, instant, no side effects):
| Tool | Use when |
|------|----------|
| \`knit_load_session\` | First call every session. Returns last sessions, handoff, learnings, false positives. |
| \`knit_query_imports\` | Before editing — what depends on this file? |
| \`knit_query_dependents\` | What does this file need to work? |
| \`knit_query_exports\` | Find a function without opening the file. |
| \`knit_query_tests\` | Is this tested? Or: list all untested files. |
| \`knit_find_fanout\` | High-risk files — change carefully. |
| \`knit_search_learnings\` | Did we solve this before? |
| \`knit_search_sessions\` | Did a past session work in this area? |
| \`knit_get_false_positives\` | Filter known non-issues out of review prompts. |
| \`knit_brain_status\` | Brain health + hit-rate + token-accounting. |
| \`knit_get_workflow\` | Fetch protocol depth for a specific phase. |

**Update the brain** (only when there's real signal):
| Tool | Use when |
|------|----------|
| \`knit_classify_task\` | At task start. Returns tier + phases. |
| \`knit_build_context\` | Get cross-domain ripple + pitfalls for the current task. |
| \`knit_record_learning\` | A non-obvious, reusable insight surfaced (pass the quality check first). |
| \`knit_record_false_positive\` | Review agent flagged a non-issue. |
| \`knit_save_session_summary\` | Session accomplished something a future session would search for. |
| \`knit_save_handoff\` | Context degrading — save state for next session. |
| \`knit_setup_project\` | First-time project setup for non-code domains (legal, research, marketing). |

**Team orchestration** (for parallel review boards):
| Tool | Use when |
|------|----------|
| \`knit_get_teams\` | Get auto-detected or custom teams. |
| \`knit_define_team\` | Create a custom team. |
| \`knit_start_team_review\` | Start a parallel review board. |
| \`knit_post_team_findings\` | Each team posts to the shared board. |
| \`knit_get_board_summary\` | Cross-team findings, severity-gated. |`;
}
